import { useCopyText } from './useCopyText'

/**
 * Copy a deep link to a song. In production the link points at the static
 * share page /s/<slug>/ (generated by scripts/song-share-pages.ts), so social
 * scrapers — which never see #hash fragments — get the song's own og: tags;
 * the page itself instantly redirects visitors to #song-<slug>. The dev server
 * has no generated pages, so there we fall back to the plain hash link.
 * `copied` stays true for a couple of seconds after each copy — drive the
 * "link copied" notice with it.
 */
export function useCopyTrackLink(slug: string) {
  const { copied, copy: copyText } = useCopyText()

  const copy = () => {
    const { origin } = window.location
    const url = import.meta.env.DEV
      ? `${origin}${import.meta.env.BASE_URL}#song-${slug}`
      : `${origin}${import.meta.env.BASE_URL}s/${slug}/`
    return copyText(url)
  }

  return { copied, copy }
}
